
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of CollaborationsRequest133
 *
 * @constructor
 */
function CollaborationsRequest133() {
    this.item = null;     
    this.accessibleBy = null;     
    this.role = null;     
    //Append to variable dictionary
    this._variableDict['accessibleBy'] = 'accessible_by';
}

CollaborationsRequest133.prototype = new BaseModel();
CollaborationsRequest133.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
CollaborationsRequest133.prototype.getItem = function() {
    return this.item;
};

/**
 * Setter for Item
 * 
 * @param {mixed} value 
 */
CollaborationsRequest133.prototype.setItem = function(value) {
    this.item = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
CollaborationsRequest133.prototype.getAccessibleBy = function() {
    return this.accessibleBy;
};

/**
 * Setter for AccessibleBy
 * 
 * @param {mixed} value 
 */
CollaborationsRequest133.prototype.setAccessibleBy = function(value) {
    this.accessibleBy = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest133.prototype.getRole = function() {
    return this.role;
};

/**
 * Setter for Role
 * 
 * @param {string} value 
 */
CollaborationsRequest133.prototype.setRole = function(value) {
    this.role = value;
};

module.exports = CollaborationsRequest133;