
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of CollaborationsRequest
 *
 * @constructor
 */
function CollaborationsRequest() {
    this.type = null;     
    this.id = null;     
    this.createdBy = null;     
    this.createdAt = null;     
    this.modifiedAt = null;     
    this.expiresAt = null;     
    this.status = null;     
    this.accessibleBy = null;     
    this.role = null;     
    this.acknowledgedAt = null;     
    this.item = null;     
    //Append to variable dictionary
    this._variableDict['createdBy'] = 'created_by';
    this._variableDict['createdAt'] = 'created_at';
    this._variableDict['modifiedAt'] = 'modified_at';
    this._variableDict['expiresAt'] = 'expires_at';
    this._variableDict['accessibleBy'] = 'accessible_by';
    this._variableDict['acknowledgedAt'] = 'acknowledged_at';
}

CollaborationsRequest.prototype = new BaseModel();
CollaborationsRequest.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getType = function() {
    return this.type;
};

/**
 * Setter for Type
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setType = function(value) {
    this.type = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
CollaborationsRequest.prototype.getCreatedBy = function() {
    return this.createdBy;
};

/**
 * Setter for CreatedBy
 * 
 * @param {mixed} value 
 */
CollaborationsRequest.prototype.setCreatedBy = function(value) {
    this.createdBy = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getModifiedAt = function() {
    return this.modifiedAt;
};

/**
 * Setter for ModifiedAt
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setModifiedAt = function(value) {
    this.modifiedAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getExpiresAt = function() {
    return this.expiresAt;
};

/**
 * Setter for ExpiresAt
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setExpiresAt = function(value) {
    this.expiresAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getStatus = function() {
    return this.status;
};

/**
 * Setter for Status
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setStatus = function(value) {
    this.status = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
CollaborationsRequest.prototype.getAccessibleBy = function() {
    return this.accessibleBy;
};

/**
 * Setter for AccessibleBy
 * 
 * @param {mixed} value 
 */
CollaborationsRequest.prototype.setAccessibleBy = function(value) {
    this.accessibleBy = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getRole = function() {
    return this.role;
};

/**
 * Setter for Role
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setRole = function(value) {
    this.role = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CollaborationsRequest.prototype.getAcknowledgedAt = function() {
    return this.acknowledgedAt;
};

/**
 * Setter for AcknowledgedAt
 * 
 * @param {string} value 
 */
CollaborationsRequest.prototype.setAcknowledgedAt = function(value) {
    this.acknowledgedAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
CollaborationsRequest.prototype.getItem = function() {
    return this.item;
};

/**
 * Setter for Item
 * 
 * @param {mixed} value 
 */
CollaborationsRequest.prototype.setItem = function(value) {
    this.item = value;
};

module.exports = CollaborationsRequest;