
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of CommentsRequest
 *
 * @constructor
 */
function CommentsRequest() {
    this.message = null;     
    this.item = null;     
}

CommentsRequest.prototype = new BaseModel();
CommentsRequest.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CommentsRequest.prototype.getMessage = function() {
    return this.message;
};

/**
 * Setter for Message
 * 
 * @param {string} value 
 */
CommentsRequest.prototype.setMessage = function(value) {
    this.message = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
CommentsRequest.prototype.getItem = function() {
    return this.item;
};

/**
 * Setter for Item
 * 
 * @param {mixed} value 
 */
CommentsRequest.prototype.setItem = function(value) {
    this.item = value;
};

module.exports = CommentsRequest;