
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of CommentUpdate
 *
 * @constructor
 */
function CommentUpdate() {
    this.message = null;     
}

CommentUpdate.prototype = new BaseModel();
CommentUpdate.prototype.constructor = BaseModel;

/**
 * The desired text for the comment message.
 *
 * @return {string|null}
 */
CommentUpdate.prototype.getMessage = function() {
    return this.message;
};

/**
 * Setter for Message
 * 
 * @param {string|null} value 
 */
CommentUpdate.prototype.setMessage = function(value) {
    this.message = value;
};

module.exports = CommentUpdate;