
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of FileVersionPromote
 *
 * @constructor
 */
function FileVersionPromote() {
    this.type = null;     
    this.id = null;     
}

FileVersionPromote.prototype = new BaseModel();
FileVersionPromote.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
FileVersionPromote.prototype.getType = function() {
    return this.type;
};

/**
 * Setter for Type
 * 
 * @param {string|null} value 
 */
FileVersionPromote.prototype.setType = function(value) {
    this.type = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
FileVersionPromote.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string|null} value 
 */
FileVersionPromote.prototype.setId = function(value) {
    this.id = value;
};

module.exports = FileVersionPromote;