
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of FileInformationUpdate
 *
 * @constructor
 */
function FileInformationUpdate() {
    this.name = null;     
    this.description = null;     
    this.parent = null;     
    this.sharedLink = null;     
    this.tags = null;     
    //Append to variable dictionary
    this._variableDict['sharedLink'] = 'shared_link';
}

FileInformationUpdate.prototype = new BaseModel();
FileInformationUpdate.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
FileInformationUpdate.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string|null} value 
 */
FileInformationUpdate.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
FileInformationUpdate.prototype.getDescription = function() {
    return this.description;
};

/**
 * Setter for Description
 * 
 * @param {string|null} value 
 */
FileInformationUpdate.prototype.setDescription = function(value) {
    this.description = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Parent95|null}
 */
FileInformationUpdate.prototype.getParent = function() {
    return this.parent;
};

/**
 * Setter for Parent
 * 
 * @param {Parent95|null} value 
 */
FileInformationUpdate.prototype.setParent = function(value) {
    this.parent = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {SharedLink96|null}
 */
FileInformationUpdate.prototype.getSharedLink = function() {
    return this.sharedLink;
};

/**
 * Setter for SharedLink
 * 
 * @param {SharedLink96|null} value 
 */
FileInformationUpdate.prototype.setSharedLink = function(value) {
    this.sharedLink = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed|null}
 */
FileInformationUpdate.prototype.getTags = function() {
    return this.tags;
};

/**
 * Setter for Tags
 * 
 * @param {mixed|null} value 
 */
FileInformationUpdate.prototype.setTags = function(value) {
    this.tags = value;
};

module.exports = FileInformationUpdate;