
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of FoldersRequest
 *
 * @constructor
 */
function FoldersRequest() {
    this.name = null;     
    this.parent = null;     
}

FoldersRequest.prototype = new BaseModel();
FoldersRequest.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FoldersRequest.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
FoldersRequest.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
FoldersRequest.prototype.getParent = function() {
    return this.parent;
};

/**
 * Setter for Parent
 * 
 * @param {mixed} value 
 */
FoldersRequest.prototype.setParent = function(value) {
    this.parent = value;
};

module.exports = FoldersRequest;