
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of GroupsRequest
 *
 * @constructor
 */
function GroupsRequest() {
    this.name = null;     
}

GroupsRequest.prototype = new BaseModel();
GroupsRequest.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GroupsRequest.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
GroupsRequest.prototype.setName = function(value) {
    this.name = value;
};

module.exports = GroupsRequest;