
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Group226
 *
 * @constructor
 */
function Group226() {
    this.id = null;     
}

Group226.prototype = new BaseModel();
Group226.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Group226.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string|null} value 
 */
Group226.prototype.setId = function(value) {
    this.id = value;
};

module.exports = Group226;