
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Group211
 *
 * @constructor
 */
function Group211() {
    this.type = null;     
    this.id = null;     
    this.name = null;     
    this.createdAt = null;     
    this.modifiedAt = null;     
    //Append to variable dictionary
    this._variableDict['createdAt'] = 'created_at';
    this._variableDict['modifiedAt'] = 'modified_at';
}

Group211.prototype = new BaseModel();
Group211.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Group211.prototype.getType = function() {
    return this.type;
};

/**
 * Setter for Type
 * 
 * @param {string|null} value 
 */
Group211.prototype.setType = function(value) {
    this.type = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Group211.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string|null} value 
 */
Group211.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Group211.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string|null} value 
 */
Group211.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Group211.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string|null} value 
 */
Group211.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Group211.prototype.getModifiedAt = function() {
    return this.modifiedAt;
};

/**
 * Setter for ModifiedAt
 * 
 * @param {string|null} value 
 */
Group211.prototype.setModifiedAt = function(value) {
    this.modifiedAt = value;
};

module.exports = Group211;