
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of NewEmailAlias
 *
 * @constructor
 */
function NewEmailAlias() {
    this.email = null;     
}

NewEmailAlias.prototype = new BaseModel();
NewEmailAlias.prototype.constructor = BaseModel;

/**
 * The email address to add to the account as an alias.
 *
 * @return {string|null}
 */
NewEmailAlias.prototype.getEmail = function() {
    return this.email;
};

/**
 * Setter for Email
 * 
 * @param {string|null} value 
 */
NewEmailAlias.prototype.setEmail = function(value) {
    this.email = value;
};

module.exports = NewEmailAlias;