
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of NewFolder
 *
 * @constructor
 */
function NewFolder() {
    this.name = null;     
    this.parent = null;     
    this.id = null;     
}

NewFolder.prototype = new BaseModel();
NewFolder.prototype.constructor = BaseModel;

/**
 * The new name for this item.
 *
 * @return {string|null}
 */
NewFolder.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string|null} value 
 */
NewFolder.prototype.setName = function(value) {
    this.name = value;
};

/**
 * The new parent folder for this item.
 *
 * @return {mixed|null}
 */
NewFolder.prototype.getParent = function() {
    return this.parent;
};

/**
 * Setter for Parent
 * 
 * @param {mixed|null} value 
 */
NewFolder.prototype.setParent = function(value) {
    this.parent = value;
};

/**
 * The id of the new parent folder.
 *
 * @return {string|null}
 */
NewFolder.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string|null} value 
 */
NewFolder.prototype.setId = function(value) {
    this.id = value;
};

module.exports = NewFolder;