
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of NewGroupMembership
 *
 * @constructor
 */
function NewGroupMembership() {
    this.user = null;     
    this.group = null;     
}

NewGroupMembership.prototype = new BaseModel();
NewGroupMembership.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {User225|null}
 */
NewGroupMembership.prototype.getUser = function() {
    return this.user;
};

/**
 * Setter for User
 * 
 * @param {User225|null} value 
 */
NewGroupMembership.prototype.setUser = function(value) {
    this.user = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Group226|null}
 */
NewGroupMembership.prototype.getGroup = function() {
    return this.group;
};

/**
 * Setter for Group
 * 
 * @param {Group226|null} value 
 */
NewGroupMembership.prototype.setGroup = function(value) {
    this.group = value;
};

module.exports = NewGroupMembership;