
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Parent95
 *
 * @constructor
 */
function Parent95() {
    this.id = null;     
}

Parent95.prototype = new BaseModel();
Parent95.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Parent95.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
Parent95.prototype.setId = function(value) {
    this.id = value;
};

module.exports = Parent95;