
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of SharedLink96
 *
 * @constructor
 */
function SharedLink96() {
    this.access = null;     
    this.unsharedAt = null;     
    this.permissions = null;     
    this.permissionsDownload = null;     
    this.permissionsPreview = null;     
    //Append to variable dictionary
    this._variableDict['unsharedAt'] = 'unshared_at';
    this._variableDict['permissionsDownload'] = 'permissions.download';
    this._variableDict['permissionsPreview'] = 'permissions.preview';
}

SharedLink96.prototype = new BaseModel();
SharedLink96.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
SharedLink96.prototype.getAccess = function() {
    return this.access;
};

/**
 * Setter for Access
 * 
 * @param {string|null} value 
 */
SharedLink96.prototype.setAccess = function(value) {
    this.access = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
SharedLink96.prototype.getUnsharedAt = function() {
    return this.unsharedAt;
};

/**
 * Setter for UnsharedAt
 * 
 * @param {string|null} value 
 */
SharedLink96.prototype.setUnsharedAt = function(value) {
    this.unsharedAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed|null}
 */
SharedLink96.prototype.getPermissions = function() {
    return this.permissions;
};

/**
 * Setter for Permissions
 * 
 * @param {mixed|null} value 
 */
SharedLink96.prototype.setPermissions = function(value) {
    this.permissions = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool|null}
 */
SharedLink96.prototype.getPermissionsDownload = function() {
    return this.permissionsDownload;
};

/**
 * Setter for PermissionsDownload
 * 
 * @param {bool|null} value 
 */
SharedLink96.prototype.setPermissionsDownload = function(value) {
    this.permissionsDownload = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool|null}
 */
SharedLink96.prototype.getPermissionsPreview = function() {
    return this.permissionsPreview;
};

/**
 * Setter for PermissionsPreview
 * 
 * @param {bool|null} value 
 */
SharedLink96.prototype.setPermissionsPreview = function(value) {
    this.permissionsPreview = value;
};

module.exports = SharedLink96;