/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */

var StatusEnum = {

    //TODO: Write general description for this element
    ACCEPTED : "accepted",

    //TODO: Write general description for this element
    REJECTED : "rejected",

    //TODO: Write general description for this element
    PENDING : "pending"

};

module.exports = StatusEnum;