/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */

var StreamTypeEnum = {

    //TODO: Write general description for this element
    ALL : "all",

    //TODO: Write general description for this element
    CHANGES : "changes",

    //TODO: Write general description for this element
    SYNC : "sync",

    //TODO: Write general description for this element
    ADMIN_LOGS : "admin_logs"

};

module.exports = StreamTypeEnum;