
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TaskAssignmentUpdate
 *
 * @constructor
 */
function TaskAssignmentUpdate() {
    this.message = null;     
    this.resolutionState = null;     
    //Append to variable dictionary
    this._variableDict['resolutionState'] = 'resolution_state';
}

TaskAssignmentUpdate.prototype = new BaseModel();
TaskAssignmentUpdate.prototype.constructor = BaseModel;

/**
 * A message from the assignee about this task.
 *
 * @return {string|null}
 */
TaskAssignmentUpdate.prototype.getMessage = function() {
    return this.message;
};

/**
 * Setter for Message
 * 
 * @param {string|null} value 
 */
TaskAssignmentUpdate.prototype.setMessage = function(value) {
    this.message = value;
};

/**
 * Can be 'completed', 'incomplete', 'approved', or 'rejected'.
 *
 * @return {string|null}
 */
TaskAssignmentUpdate.prototype.getResolutionState = function() {
    return this.resolutionState;
};

/**
 * Setter for ResolutionState
 * 
 * @param {string|null} value 
 */
TaskAssignmentUpdate.prototype.setResolutionState = function(value) {
    this.resolutionState = value;
};

module.exports = TaskAssignmentUpdate;