
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TaskUpdate
 *
 * @constructor
 */
function TaskUpdate() {
    this.action = null;     
    this.message = null;     
    this.dueAt = null;     
    //Append to variable dictionary
    this._variableDict['dueAt'] = 'due_at';
}

TaskUpdate.prototype = new BaseModel();
TaskUpdate.prototype.constructor = BaseModel;

/**
 * The action the task assignee will be prompted to do. Can be 'review'.
 *
 * @return {string|null}
 */
TaskUpdate.prototype.getAction = function() {
    return this.action;
};

/**
 * Setter for Action
 * 
 * @param {string|null} value 
 */
TaskUpdate.prototype.setAction = function(value) {
    this.action = value;
};

/**
 * An optional message to include with the task.
 *
 * @return {string|null}
 */
TaskUpdate.prototype.getMessage = function() {
    return this.message;
};

/**
 * Setter for Message
 * 
 * @param {string|null} value 
 */
TaskUpdate.prototype.setMessage = function(value) {
    this.message = value;
};

/**
 * The day at which this task is due.
 *
 * @return {string|null}
 */
TaskUpdate.prototype.getDueAt = function() {
    return this.dueAt;
};

/**
 * Setter for DueAt
 * 
 * @param {string|null} value 
 */
TaskUpdate.prototype.setDueAt = function(value) {
    this.dueAt = value;
};

module.exports = TaskUpdate;