
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TaskAssignmentsRequest
 *
 * @constructor
 */
function TaskAssignmentsRequest() {
    this.task = null;     
    this.assignTo = null;     
    //Append to variable dictionary
    this._variableDict['assignTo'] = 'assign_to';
}

TaskAssignmentsRequest.prototype = new BaseModel();
TaskAssignmentsRequest.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
TaskAssignmentsRequest.prototype.getTask = function() {
    return this.task;
};

/**
 * Setter for Task
 * 
 * @param {mixed} value 
 */
TaskAssignmentsRequest.prototype.setTask = function(value) {
    this.task = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {mixed}
 */
TaskAssignmentsRequest.prototype.getAssignTo = function() {
    return this.assignTo;
};

/**
 * Setter for AssignTo
 * 
 * @param {mixed} value 
 */
TaskAssignmentsRequest.prototype.setAssignTo = function(value) {
    this.assignTo = value;
};

module.exports = TaskAssignmentsRequest;