
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of UpdateMembership
 *
 * @constructor
 */
function UpdateMembership() {
    this.role = null;     
}

UpdateMembership.prototype = new BaseModel();
UpdateMembership.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
UpdateMembership.prototype.getRole = function() {
    return this.role;
};

/**
 * Setter for Role
 * 
 * @param {string|null} value 
 */
UpdateMembership.prototype.setRole = function(value) {
    this.role = value;
};

module.exports = UpdateMembership;