
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of UsersRequest
 *
 * @constructor
 */
function UsersRequest() {
    this.login = null;     
    this.name = null;     
}

UsersRequest.prototype = new BaseModel();
UsersRequest.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
UsersRequest.prototype.getLogin = function() {
    return this.login;
};

/**
 * Setter for Login
 * 
 * @param {string} value 
 */
UsersRequest.prototype.setLogin = function(value) {
    this.login = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
UsersRequest.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
UsersRequest.prototype.setName = function(value) {
    this.name = value;
};

module.exports = UsersRequest;