
/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of User225
 *
 * @constructor
 */
function User225() {
    this.id = null;     
}

User225.prototype = new BaseModel();
User225.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User225.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string|null} value 
 */
User225.prototype.setId = function(value) {
    this.id = value;
};

module.exports = User225;