/**
 * BoxLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/07/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://api.box.com/{0}",

    //TODO: Replace the Version with an appropriate value
    version : "TODO: Replace",

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the OAuthAccessToken with an appropriate value
    oAuthAccessToken : "TODO: Replace"

};

module.exports = configuration;

